name: Deploy kafka topics to PROD
on:
  workflow_dispatch:

env:
  TOPIC_FILE: .nais/kafka/kafka-prod.yaml

jobs:
  deploy-to-prod:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Deploy topics to PROD
        uses: nais/deploy/actions/deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: prod-gcp
          RESOURCE: ${{ env.TOPIC_FILE }}
